# Generated by Django 4.1.4 on 2022-12-15 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("date_reserved", models.DateTimeField(blank=True, null=True)),
                ("destination", models.CharField(blank=True, max_length=50)),
                ("capacity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Seats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_id", models.CharField(blank=True, max_length=10)),
                ("available", models.BooleanField(default=True)),
                (
                    "date_reserved",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reserved date"
                    ),
                ),
                ("destination", models.CharField(blank=True, max_length=50)),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight_api.flight",
                    ),
                ),
            ],
        ),
    ]
