# Generated by Django 4.1.4 on 2022-12-15 17:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flight_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Seats",
            new_name="SeatMap",
        ),
    ]
