# Generated by Django 4.1.4 on 2022-12-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_api', '0002_rename_seats_seatmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
